name: Validate Documentation Structure

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run critical documentation validation
        run: node validate-docs-structure.js --only-critical
        
      - name: Run full documentation validation
        run: node validate-docs-structure.js
        continue-on-error: true
        
      - name: Comment on PR with validation results
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Documentation structure validation failed. Please check the logs and fix the issues before merging.'
            }) 